# Default values for etcd-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
namespace: etcd
storage:
  datasize: 50Gi
  provisioner: kubernetes.io/gce-pd
  type: "ssd-disk"
cron:
  defragschedule: 0 2 * * *
  commandtimeout: 120s

args:
  auto-compaction-retention: 1
  data-dir: /var/run/etcd/default.etcd
  quota-backend-bytes: 8589934592

image:
  repository: k8s.gcr.io/etcd-amd64
  tag: 3.3.10
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

istioEnabled: false
