apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-defrag-cron
  namespace: {{.Values.namespace}}
spec:
  schedule: "{{.Values.cron.defragschedule}}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: etcd
              image: "k8s.gcr.io/etcd-amd64:3.2.26"
              args:
                - /bin/sh
                - -c
                - -x
                - -e
                - |
                  etcdctl="etcdctl --command-timeout={{.Values.cron.commandtimeout}}"
                  lb_etcd='{{.Values.servicename}}.{{.Values.namespace}}.svc.cluster.local:2379'
                  export ETCDCTL_API=3
                  members=$($etcdctl --endpoints=$lb_etcd member list)
                  endpoints=$(echo "$members" | tr ' ' '\n' | grep 2379)

                  endpoint=
                  for e in $endpoints; do
                      echo "running defrag for : $e"
                      $etcdctl --endpoints="$e" defrag
                      $etcdctl --endpoints="$e" --write-out=table endpoint status
                      endpoint=$e
                  done;

                  echo "running disarm against : $endpoint"
                  $etcdctl --endpoints="$endpoint" alarm disarm
                  $etcdctl --endpoints="$endpoint" alarm list
          restartPolicy: OnFailure
