apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-disk
  namespace: {{.Values.namespace}}
provisioner: {{.Values.storage.provisioner}}
parameters:
  type: {{.Values.storage.type}}
