{{ if .Values.istioEnabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: etcd-client
  namespace: {{.Values.namespace}}
spec:
  hosts:
    - etcd
  tcp:
    - route:
        - destination:
            host: etcd
            port:
              number: 2379
    - route:
        - destination:
            host: etcd
            port:
              number: 2380
{{ end }}
